#!/usr/bin/env ruby

require 'fileutils'
require 'erb'
require_relative 'lib/seo'

TEMPLATE     = File.join(File.dirname(__FILE__), 'templates/sitemap.xml.erb')
SEO_URLS  = File.join(ARGV[0],'src/seo-urls.yaml')
REDIRECT_SITEMAP  = File.join(ARGV[0],'src/sitemap-redirected-urls.txt')

if File.exist?(REDIRECT_SITEMAP)
  FileUtils.cp(REDIRECT_SITEMAP, File.join(ARGV[0],'dist/sitemap-redirected-urls.txt'))
end

SITEMAP_XML  = File.join(ARGV[0],'dist/sitemap.xml')

# Empty sitemap.xml
erb = ERB.new(File.read(TEMPLATE)).result()
File.write(SITEMAP_XML, erb)

# if File.exist?(SEO_URLS) && (ENV['BASE_ENV'] == 'production' || ENV['FORCE_SITEMAP'])
#   erb = ERB.new(File.read(TEMPLATE)).result(Seo.new(SEO_URLS).context)
#   File.write(SITEMAP_XML, erb)
# end
